# Connessione PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/tornei
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurazione JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=true

# Disabilita cache Thymeleaf
spring.thymeleaf.cache=false